FROM elasticsearch:5.6.16-alpine

# RUN /usr/share/elasticsearch/bin/plugin install analysis-phonetic
# RUN /usr/share/elasticsearch/bin/plugin install analysis-icu

USER root
RUN echo "vm.max_map_count=262144" >> /etc/sysctl.conf
